<div class="row">
    <div class="col">
        <h1>Cadastro de Fornecedores</h1>
    </div>
</div>

<form class="needs-validation" novalidate action="<?=$this->basePath('/fornecedor/add')?>" method="POST">
    <div class="form-row mb-3">
        <div class="col">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" value="1" id="rdPessoaFisica" name="tipoFornecedor" class="custom-control-input" checked>
                <label class="custom-control-label" for="rdPessoaFisica">Pessoa física</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" value="2" id="rdPessoaJuridica" name="tipoFornecedor" class="custom-control-input">
                <label class="custom-control-label" for="rdPessoaJuridica">Pessoa Jurídica</label>
            </div>
        </div>
    </div>

    <div class="form-row mb-3">
        <div class="col-md-3">
            <label for="empresaFornecedor">Empresas</label>
            <select id="empresaFornecedor" name="EMPRESA" class="form-control" required>
                <option value="">Selecione</option>
                <?php
                foreach($empresas as $key => $value){ ?>
                    <option value="<?=$key?>" data-uf="<?=$value['uf']?>"><?=$value['nome']. ' - '.$value['uf']?></option>
                <?php 
                } ?>
            </select>
        </div>
    </div>
    
    <div class="form-row mb-3">
        <div class="col-md-2">
            <label for="cnpjFornecedor">CPF/CNPJ</label>
            <input type="text" class="form-control" id="cnpjFornecedor" name="FORNECEDOR" placeholder="CPF/CNPJ" required>
            <div class="invalid-feedback">
                Informe o CPF/CNPJ
            </div>
        </div>

        <div class="col-md-5">
            <label for="nomeFantasia">Nome</label>
            <input type="text" class="form-control" id="nomeFantasia" name="NOME" placeholder="Nome" required maxlength="150">
            <div class="invalid-feedback">
                Informe o nome
            </div>
        </div>

        <div class="col-md-2">
            <label for="rgFornecedor">RG</label>
            <input type="text" class="form-control" id="rgFornecedor" name="RG" placeholder="RG" required>
            <div class="invalid-feedback">
                Informe o RG
            </div>
        </div>

        <div class="col-md-2">
            <label for="dtNascimentoFornecedor">Data Nascimento</label>
            <input type="date" class="form-control" id="dtNascimentoFornecedor" name="DATA_NASCIMENTO" required placeholder="Data Nascimento">
            <div class="invalid-feedback">
                Informe a data de nascimento
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-1">
            <a href="<?=$this->basePath('/fornecedor')?>" class="btn btn-danger">
                Cancelar
            </a>
        </div>

        <div class="col-2">
            <button type="submit" class="btn btn-primary" id="submitbutton" name="submitbutton" value="Go">
                Salvar fornecedor
            </button>
        </div>
    </div>
</form>

<script>
    $(document).ready(function(){
        $('input[name^="tipoFornecedor"]').on('change', function(){
            $('#rgFornecedor').prop('required', false)
            $('#dtNascimentoFornecedor').prop('required', false)
                
            if(this.value == 1){
                $('#rgFornecedor').prop('required', true)
                $('#dtNascimentoFornecedor').prop('required', true)
            }
        })
    });
    
    (function() {
        'use strict';
        window.addEventListener('load', function() {            
            let forms = document.getElementsByClassName('needs-validation');

            let validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }

                    let estado = $('#empresaFornecedor').find('option:selected').data().uf;
                    let tipoFornecedor = $('input[name^="tipoFornecedor"]').val()

                    if(estado == 'PR' && tipoFornecedor == 1){
                        let dataNascimento = $('#dtNascimentoFornecedor').val().split('-')

                        const dataAtual     = new Date();
                        dataNascimento      = new Date(dataNascimento[0], dataNascimento[1], dataNascimento[2]);
                        const diffTime  = Math.abs(dataNascimento.getTime() - dataAtual.getTime());
                        const diffDays  = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
                       
                        if(diffDays <= 6570){ //Valor aproximado em dias
                            Swal.fire({
                                type: 'error',
                                title: 'Oops...',
                                text: 'Empresas do Paraná o fornecedor deve ser maior de idade!'
                            })

                            event.preventDefault();
                            event.stopPropagation();
                        }
                    }

                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>