<div class="row mb-4">
    <div class="col-md-12">
        <h1>SISTEMA DE FORNECEDORES</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <a href="<?=$this->basePath('/empresa')?>" class="btn btn-primary">
            Acessar empresas
        </a>    
    </div>

    <div class="col-md-3">
        <a href="<?=$this->basePath('/fornecedor')?>" class="btn btn-primary">
            Acessar fornecedores
        </a>    
    </div>
</div>
